import os
import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command

BOT_TOKEN = os.getenv("BOT_TOKEN")
bot = Bot(token=BOT_TOKEN)
dp = Dispatcher()

PROJECT_FOLDER = "."  # GitHub repo-ның іші

@dp.message(Command("start"))
async def start(message: types.Message):
    await message.answer(
        "🚀 **CodeGrokBot + Cloud Pro**\n\n"
        "Код жаз → ол бірден GitHub-қа сақталады → Codespaces-те көресің!\n\n"
        "Қандай код керек?"
    )

@dp.message()
async def generate(message: types.Message):
    user_text = message.text
    await message.answer("🤖 Код жазып, GitHub-қа сақтап жатырмын...")

    code = f"""# Generated by CodeGrokBot
# Сұрау: {user_text}

print("✅ {user_text} дайын! Cloud Pro-да жұмыс істеп тұр.")

def main():
    print("Бұл жерге толық код келеді...")

if __name__ == "__main__":
    main()
"""

    filename = f"generated_{asyncio.get_event_loop().time():.0f}.py"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(code)

    await message.answer(
        f"✅ **Код сақталды!**\n\n"
        f"📁 Файл: `{filename}`\n\n"
        f"GitHub-қа жүктелді. Codespaces-те бірден көрінуі керек."
    )

async def main():
    print("Bot + Cloud Pro integration started...")
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())
